HEADERS += \
    $$PWD/sources/mainwindow.h \
    $$PWD/sources/log.h \
    $$PWD/sources/slot/dayincomequery_dialog.h \
    $$PWD/sources/slot/add_reduce_dialog.h \
    $$PWD/sources/slot/staffregister_dialog.h \
    $$PWD/sources/slot/varietymenu_dialog.h \
    $$PWD/sources/slot/dishescount_dialog.h \
    $$PWD/sources/slot/foodinfo_dialog.h \
    $$PWD/sources/slot/monthincomequery_dialog.h \
    $$PWD/sources/slot/selectseat_dialog.h \
    $$PWD/sources/slot/stockqquery_dialog.h \
    $$PWD/sources/slot/check_out_dialog.h \
    $$PWD/sources/slot/orderdishes_dialog.h \
    $$PWD/sources/ui/ui_stockquery_dialog.h \
    $$PWD/sources/ui/ui_mainwindow.h \
    $$PWD/sources/ui/ui_foodinfo_dialog.h \
    $$PWD/sources/ui/ui_add_reduce_dialog.h \
    $$PWD/sources/ui/ui_orderdishes_dialog.h \
    $$PWD/sources/ui/ui_monthincomequery_dialog.h \
    $$PWD/sources/ui/ui_selectseat_dialog.h \
    $$PWD/sources/ui/ui_staffregister_dialog.h \
    $$PWD/sources/ui/ui_check_out_dialog.h \
    $$PWD/sources/ui/ui_dayincomequery_dialog.h \
    $$PWD/sources/ui/ui_dishescount_dialog.h \
    $$PWD/sources/ui/ui_varietymenu_dialog.h \
    $$PWD/sources/db/day_statistics.h \
    $$PWD/sources/db/order_dishes.h \
    $$PWD/sources/db/food_info.h \
    $$PWD/sources/db/user_management.h \
    $$PWD/sources/db/seat_info.h \
    $$PWD/sources/db/check.h \
    $$PWD/sources/db/manage_database.h \
    $$PWD/sources/db/sales.h \
    $$PWD/sources/model/account.h \
    $$PWD/sources/slot/login_slot.h \
    $$PWD/sources/ui/login_dlg_ui.h \
    $$PWD/sources/service/init_db_service.h \
    $$PWD/sources/service/account_service.h \
    $$PWD/sources/service/sql_file_service.h \
    $$PWD/sources/db/search_table_db.h

SOURCES += \
    $$PWD/sources/main.cpp \
    $$PWD/sources/mainwindow.cpp \
    $$PWD/sources/log.cpp \
    $$PWD/sources/slot/selectseat_dialog.cpp \
    $$PWD/sources/slot/varietymenu_dialog.cpp \
    $$PWD/sources/slot/stockqquery_dialog.cpp \
    $$PWD/sources/slot/foodinfo_dialog.cpp \
    $$PWD/sources/slot/add_reduce_dialog.cpp \
    $$PWD/sources/slot/dayincomequery_dialog.cpp \
    $$PWD/sources/slot/check_out_dialog.cpp \
    $$PWD/sources/slot/orderdishes_dialog.cpp \
    $$PWD/sources/slot/dishescount_dialog.cpp \
    $$PWD/sources/slot/staffregister_dialog.cpp \
    $$PWD/sources/slot/monthincomequery_dialog.cpp \
    $$PWD/sources/ui/ui_dishescount_dialog.cpp \
    $$PWD/sources/ui/ui_staffregister_dialog.cpp \
    $$PWD/sources/ui/ui_selectseat_dialog.cpp \
    $$PWD/sources/ui/ui_add_reduce_dialog.cpp \
    $$PWD/sources/ui/ui_dayincomequery_dialog.cpp \
    $$PWD/sources/ui/ui_mainwindow.cpp \
    $$PWD/sources/ui/ui_varietymenu_dialog.cpp \
    $$PWD/sources/ui/ui_check_out_dialog.cpp \
    $$PWD/sources/ui/ui_monthincomequery_dialog.cpp \
    $$PWD/sources/ui/ui_orderdishes_dialog.cpp \
    $$PWD/sources/ui/ui_foodinfo_dialog.cpp \
    $$PWD/sources/ui/ui_stockquery_dialog.cpp \
    $$PWD/sources/db/day_statistics.cpp \
    $$PWD/sources/db/order_dishes.cpp \
    $$PWD/sources/db/food_info.cpp \
    $$PWD/sources/db/user_management.cpp \
    $$PWD/sources/db/seat_info.cpp \
    $$PWD/sources/db/check.cpp \
    $$PWD/sources/db/manage_database.cpp \
    $$PWD/sources/db/sales.cpp \
    $$PWD/sources/model/account.cpp \
    $$PWD/sources/slot/login_slot.cpp \
    $$PWD/sources/ui/login_dlg_ui.cpp \
    $$PWD/sources/service/account_service.cpp \
    $$PWD/sources/service/init_db_service.cpp \
    $$PWD/sources/service/sql_file_service.cpp \
    $$PWD/sources/db/search_table_db.cpp
