HEADERS += \
    $$PWD/include/mainwindow.h \
    $$PWD/include/log.h \
    $$PWD/include/dialog/dayincomequery_dialog.h \
    $$PWD/include/dialog/add_reduce_dialog.h \
    $$PWD/include/dialog/staffregister_dialog.h \
    $$PWD/include/dialog/varietymenu_dialog.h \
    $$PWD/include/dialog/dishescount_dialog.h \
    $$PWD/include/dialog/foodinfo_dialog.h \
    $$PWD/include/dialog/login_dialog.h \
    $$PWD/include/dialog/monthincomequery_dialog.h \
    $$PWD/include/dialog/selectseat_dialog.h \
    $$PWD/include/dialog/stockqquery_dialog.h \
    $$PWD/include/dialog/check_out_dialog.h \
    $$PWD/include/dialog/orderdishes_dialog.h \
    $$PWD/include/ui/ui_stockquery_dialog.h \
    $$PWD/include/ui/ui_mainwindow.h \
    $$PWD/include/ui/ui_foodinfo_dialog.h \
    $$PWD/include/ui/ui_add_reduce_dialog.h \
    $$PWD/include/ui/ui_orderdishes_dialog.h \
    $$PWD/include/ui/ui_monthincomequery_dialog.h \
    $$PWD/include/ui/ui_selectseat_dialog.h \
    $$PWD/include/ui/ui_staffregister_dialog.h \
    $$PWD/include/ui/ui_login_dialog.h \
    $$PWD/include/ui/ui_check_out_dialog.h \
    $$PWD/include/ui/ui_dayincomequery_dialog.h \
    $$PWD/include/ui/ui_dishescount_dialog.h \
    $$PWD/include/ui/ui_varietymenu_dialog.h \
    $$PWD/include/db/day_statistics.h \
    $$PWD/include/db/order_dishes.h \
    $$PWD/include/db/food_info.h \
    $$PWD/include/db/user_management.h \
    $$PWD/include/db/seat_info.h \
    $$PWD/include/db/check.h \
    $$PWD/include/db/create_table.h \
    $$PWD/include/db/excute_sql_file.h \
    $$PWD/include/db/init_database.h \
    $$PWD/include/db/manage_database.h \
    $$PWD/include/db/sales.h \
    $$PWD/include/model/account.h

SOURCES += \
    $$PWD/sources/main.cpp \
    $$PWD/sources/mainwindow.cpp \
    $$PWD/sources/log.cpp \
    $$PWD/sources/dialog/selectseat_dialog.cpp \
    $$PWD/sources/dialog/login_dialog.cpp \
    $$PWD/sources/dialog/varietymenu_dialog.cpp \
    $$PWD/sources/dialog/stockqquery_dialog.cpp \
    $$PWD/sources/dialog/foodinfo_dialog.cpp \
    $$PWD/sources/dialog/add_reduce_dialog.cpp \
    $$PWD/sources/dialog/dayincomequery_dialog.cpp \
    $$PWD/sources/dialog/check_out_dialog.cpp \
    $$PWD/sources/dialog/orderdishes_dialog.cpp \
    $$PWD/sources/dialog/dishescount_dialog.cpp \
    $$PWD/sources/dialog/staffregister_dialog.cpp \
    $$PWD/sources/dialog/monthincomequery_dialog.cpp \
    $$PWD/sources/ui/ui_dishescount_dialog.cpp \
    $$PWD/sources/ui/ui_staffregister_dialog.cpp \
    $$PWD/sources/ui/ui_selectseat_dialog.cpp \
    $$PWD/sources/ui/ui_add_reduce_dialog.cpp \
    $$PWD/sources/ui/ui_dayincomequery_dialog.cpp \
    $$PWD/sources/ui/ui_login_dialog.cpp \
    $$PWD/sources/ui/ui_mainwindow.cpp \
    $$PWD/sources/ui/ui_varietymenu_dialog.cpp \
    $$PWD/sources/ui/ui_check_out_dialog.cpp \
    $$PWD/sources/ui/ui_monthincomequery_dialog.cpp \
    $$PWD/sources/ui/ui_orderdishes_dialog.cpp \
    $$PWD/sources/ui/ui_foodinfo_dialog.cpp \
    $$PWD/sources/ui/ui_stockquery_dialog.cpp \
    $$PWD/sources/db/day_statistics.cpp \
    $$PWD/sources/db/order_dishes.cpp \
    $$PWD/sources/db/food_info.cpp \
    $$PWD/sources/db/user_management.cpp \
    $$PWD/sources/db/seat_info.cpp \
    $$PWD/sources/db/check.cpp \
    $$PWD/sources/db/excute_sql_file.cpp \
    $$PWD/sources/db/create_table.cpp \
    $$PWD/sources/db/init_database.cpp \
    $$PWD/sources/db/manage_database.cpp \
    $$PWD/sources/db/sales.cpp \
    $$PWD/sources/model/account.cpp
